/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import SistemaDesktop.LinesOfCode;
import SistemaDesktop.MaxDit;
import SistemaDesktop.NumberOfAttributes;
import SistemaDesktop.NumberOfChildren;
import SistemaDesktop.NumberOfClasses;
import SistemaDesktop.NumberOfInterfaces;
import SistemaDesktop.NumberOfMethods;
import SistemaDesktop.Project;
import SistemaDesktop.XmlArchive;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Classe responsável por realizar a interface entre o programa e o usuário.
 * 
 * @author Projeto Fenix
 */
public class Interface extends javax.swing.JFrame 
{   
    private Project project;
    private NumberOfClasses numberOfClasses;
    private NumberOfInterfaces numberOfInterfaces;
    private MaxDit maxDit;
    private LinesOfCode linesOfCode;
    private NumberOfAttributes numberOfAttributes;
    private NumberOfMethods numberOfMethods;
    private NumberOfChildren numberOfChildren;
    
    /**
     * Método getter, responsável por retornar a classe que contém o número de 
     * classes do projeto.
     * 
     * @return NumberOfClasses - Corresponde à classe que contém o número de
     * classes do projeto.
     */
    public NumberOfClasses getNumberOfClasses() 
    {
        return numberOfClasses;
    }
    
    /**
     * Método getter, responsável por retornar a classe que contém o número de 
     * interfaces do projeto.
     * 
     * @return NumberOfInterfaces - Corresponde à classe que contém o número de
     * interfaces do projeto.
     */
    public NumberOfInterfaces getNumberOfInterfaces() 
    {
        return numberOfInterfaces;
    }
    
    /**
     * Método getter, responsável por retornar a classe que contém o dit máximo 
     * do projeto.
     * 
     * @return MaxDit - Corresponde à classe que contém o dit máximo do projeto.
     */
    public MaxDit getMaxDit() 
    {
        return maxDit;
    }
    
    /**
     * Método getter, responsável por retornar a classe que contém o número de 
     * linhas do projeto.
     * 
     * @return LinesOfCode - Corresponde à classe que contém o número de linhas 
     * do projeto.
     */
    public LinesOfCode getLinesOfCode() 
    {
        return linesOfCode;
    }
    
    /**
     * Método getter, responsável por retornar a classe que contém o número de 
     * atributos do projeto.
     * 
     * @return NumberOfAttributes - Corresponde à classe que contém o número de
     * atributos do projeto.
     */
    public NumberOfAttributes getNumberOfAttributes() 
    {
        return numberOfAttributes;
    }
    
    /**
     * Método getter, responsável por retornar a classe que contém o número de 
     * métodos do projeto.
     * 
     * @return NumberOfMethods - Corresponde à classe que contém o número de
     * métodos do projeto.
     */
    public NumberOfMethods getNumberOfMethods() 
    {
        return numberOfMethods;
    }
    
    /**
     * Método getter, responsável por retornar a classe que contém o número de 
     * filhos do projeto.
     * 
     * @return NumberOfChildren - Corresponde à classe que contém o número de
     * filhos do projeto.
     */
    public NumberOfChildren getNumberOfChildren() 
    {
        return numberOfChildren;
    }

    /**
     * Método construtor.
     */
    public Interface() 
    {
        initComponents();
        numberOfClasses = new NumberOfClasses();
        numberOfInterfaces = new NumberOfInterfaces();
        maxDit = new MaxDit();
        linesOfCode = new LinesOfCode();
        numberOfAttributes = new NumberOfAttributes();
        numberOfMethods = new NumberOfMethods();
        numberOfChildren = new NumberOfChildren();
       // project = new Project();
        
        this.setSize(535, 360);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        b_gerarXML = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        j_selectIFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Desktop");
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setFocusCycleRoot(true);
        jScrollPane1.setFocusable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Não sabe o que fazer? \nSelecione um diretório clicando em Arquivo->Selecionar Entrada.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setFocusable(false);
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 310, 140);

        jButton1.setText("Calcular Métricas");
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 130, 160, 40);

        jButton2.setText("Mostrar Resultados");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 180, 160, 40);

        b_gerarXML.setText("Gerar XML");
        b_gerarXML.setEnabled(false);
        b_gerarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gerarXMLActionPerformed(evt);
            }
        });
        getContentPane().add(b_gerarXML);
        b_gerarXML.setBounds(350, 230, 160, 40);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/title.png"))); // NOI18N
        getContentPane().add(title);
        title.setBounds(40, 30, 460, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-240, -40, 810, 410);

        jMenu1.setText("Arquivo");

        j_selectIFile.setText("Selecionar Pasta");
        j_selectIFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                j_selectIFileMousePressed(evt);
            }
        });
        jMenu1.add(j_selectIFile);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        jMenuItem3.setText("Desenvolvedores");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_Reminder_Icon_16.png"))); // NOI18N
        jMenuItem4.setText("Aplicação");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem4MousePressed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método responsável por realizar o cálculo das métricas.
     * 
     * @param evt - Corresponde ao clique do mouse.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try 
        {   project.firstStep();
            project.secondStep();
            project.thirdStep();

            ArrayList<SistemaDesktop.Class> classMetrics = project.getMetrics();

            numberOfClasses.calculatesMetric(classMetrics);
            numberOfInterfaces.calculatesMetric(classMetrics);
            maxDit.calculatesMetric(classMetrics);
            linesOfCode.calculatesMetric(classMetrics);
            numberOfAttributes.calculatesMetric(classMetrics);
            numberOfMethods.calculatesMetric(classMetrics);
            numberOfChildren.calculatesMetric(classMetrics);

            if (classMetrics.size() == 1)
                jTextArea1.setText("Foi encontrado "+classMetrics.size()+" arquivo.");
            else
                jTextArea1.setText("Foram encontrados "+classMetrics.size()+" arquivos.");
            jButton2.setEnabled(true);
            b_gerarXML.setEnabled(true);
        } 
        catch (IOException ex) 
        {   JOptionPane.showMessageDialog(null, "Não foi possível calcular as métricas, tente novamente.", "ERRO", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Método responsável por mostrar o resultado no log.
     * 
     * @param evt - Corresponde ao clique do mouse. 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jTextArea1.setText("");
        jTextArea1.append("Métricas do projeto");
        jTextArea1.append("\n--------------------------------------------------------");
        jTextArea1.append("\nNúmero de classes: "+numberOfClasses.getNumberOfClasses());
        jTextArea1.append("\nNúmero de interfaces: "+numberOfInterfaces.getNumberOfInterface());
        jTextArea1.append("\nDit Máximo: "+maxDit.getMaxDit());
        jTextArea1.append("\nLinhas de código: "+linesOfCode.getLinesOfCode());
        jTextArea1.append("\n--------------------------------------------------------");
        jTextArea1.append("\nMétricas de classe (média e desvio padrão)");
        jTextArea1.append("\n--------------------------------------------------------");
        jTextArea1.append(String.format("\nNúmero de atributos\nMédia: %.02f\nDesvio padrão: %.02f", numberOfAttributes.getAverage(), numberOfAttributes.getStandartDeviation()));
        jTextArea1.append("\n--------------------------------------------------------");
        jTextArea1.append(String.format("\nNúmero de métodos\nMédia: %.02f\nDesvio padrão: %.02f", numberOfMethods.getAverage(), numberOfMethods.getStandartDeviation()));
        jTextArea1.append("\n--------------------------------------------------------");
        jTextArea1.append(String.format("\nNúmero de filhos\nMédia: %.02f\nDesvio padrão: %.02f", numberOfChildren.getAverage(), numberOfChildren.getStandartDeviation()));
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Método responsável por percorrer o diretório e encontrar os arquivos
     * .java.
     * 
     * @param evt - Corresponde ao clique do mouse.
     */
    private void j_selectIFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_selectIFileMousePressed
        project = new Project();
        if (project.getFilesFolder())
            jButton1.setEnabled(true);
        else
            JOptionPane.showMessageDialog(null, "Você não escolheu nenhum diretório válido.", "Aviso", JOptionPane.INFORMATION_MESSAGE);  
    }//GEN-LAST:event_j_selectIFileMousePressed
    
    /**
     * Método responsável por informar os desenvolvedores do projeto.
     * 
     * @param evt - Corresponde ao clique do mouse.
     */
    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        
        JOptionPane.showMessageDialog(null, "Esse trabalho foi desenvolvido por:\n- Gustavo Pinho\n- João Pedro Bretanha\n- Jean Antunes\n- Ândrio Araujo\n- Felipe Prestes", "Informação - Desenvolvedores", JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_jMenuItem3MousePressed
    
    /**
     * Método responsável por informar sobre a aplicação.
     * 
     * @param evt - Corresponde ao clique do mouse.
     */
    private void jMenuItem4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MousePressed
       
        JOptionPane.showMessageDialog(null, "O sistema analisa um conjunto de arquivos .java e gera algumas métricas, definidas no escopo da disciplina de \nDesenvolvimento de Software, lecionada pelos professores Paulo Ferreira e Lisane Brisolara, em 2015/2.", "Informação - Aplicação", JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_jMenuItem4MousePressed
    
    /**
     * Método responsável por gerar o arquivo XML.
     * 
     * @param evt - Corresponde ao clique do mouse.
     */
    private void b_gerarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gerarXMLActionPerformed
        
        JFileChooser saveFile = new JFileChooser(); 
        //nome por default do xml, mesmo nome do projeto
        saveFile.setSelectedFile(new File("XML_"+project.getNameProject()));
        
        int resultado = saveFile.showSaveDialog(this);
        File file = saveFile.getSelectedFile();
        
        
        if (resultado == JFileChooser.CANCEL_OPTION) 
           return;
        else{    
            XmlArchive xml = new XmlArchive(file.getName());
            xml.generateXML(this, file.getName(), file);
            jTextArea1.setText("O arquivo xml foi criado com sucesso.");
        }
        
        //saveFile.setSelectedFile(new File("home\\jean\\xml_project.xml"));
  
    //File salvarArquivoEscolhido = salvandoArquivo.getSelectedFile();
    
        /*String answer;
        
        else if(file.getName().equals("")){
            
        }
        
        
        answer = (JOptionPane.showInputDialog("Insira o nome do projeto: "));
        if (answer == null || answer.equals("")){
            JOptionPane.showMessageDialog(null, "Você não escolheu nenhum nome para o projeto", "Aviso", JOptionPane.INFORMATION_MESSAGE);  
        }else{
            XmlArchive xml = new XmlArchive(answer);
            xml.generateXML(this, answer);
            jTextArea1.setText("O arquivo xml foi criado com sucesso.");
        }*/
    }//GEN-LAST:event_b_gerarXMLActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_gerarXML;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem j_selectIFile;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
